version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
    volumes:
      - ${DATA}:/data
    environment:
      - BADGE_NAME=${BADGE_NAME}
      - BADGE_NUMBER=${BADGE_NUMBER}
    ports:
      - 4242:4242
    image: cesfo_balance_management
    command: "/app/venv/bin/flask run --host 0.0.0.0 -p 4242"
