version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
    volumes:
      - ${DATA}:/data
    environment:
      - BADGE_NAME=${BADGE_NAME}
      - BADGE_NUMBER=${BADGE_NUMBER}
    ports:
      - 5000:5000
    image: cesfo_balance_management
