version: '3'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        UID: ${UID}
    volumes:
      - ${DATA}:/data
    ports:
      - 5000:5000
    image: cesfo_balance_management_server
    restart: always
    command: "/app/venv/bin/flask run --host 0.0.0.0 -p 5000"

  update:
    build:
      context: update_balance_history
      dockerfile: Dockerfile
      args:
        UID: ${UID}
    volumes:
      - ${DATA}:/data
    environment:
      - BADGE_NAME=${BADGE_NAME}
      - BADGE_NUMBER=${BADGE_NUMBER}
    image: cesfo_balance_management_update
    profiles:
      - update
